import { redirect } from 'next/navigation'
import { createClient } from '@/lib/supabase/server'
import { getAIvsHumanSummary, getChannelSummary } from '@/lib/revenue-attribution'

function Money({ value }: { value: number }) {
  return <>{Math.round(value).toLocaleString()} SAR</>
}

function StatCard({ title, value, sub }: { title: string; value: string; sub?: string }) {
  return (
    <div className="stat-card">
      <div className="text-slate-500 text-xs uppercase tracking-wider">{title}</div>
      <div className="font-display text-2xl font-bold text-slate-900 mt-1">{value}</div>
      {sub && <div className="text-slate-400 text-xs mt-1">{sub}</div>}
    </div>
  )
}

export default async function AIRevenuePage() {
  const supabase = createClient()

  const { data: { user } } = await supabase.auth.getUser()
  if (!user) redirect('/login')

  const { data: profile } = await supabase
    .from('profiles')
    .select('company_id, role')
    .eq('id', user.id)
    .single()

  if (!profile?.company_id) redirect('/login')

  const since = new Date()
  since.setDate(since.getDate() - 30)

  const periodStart = since.toISOString()
  const periodEnd = new Date().toISOString()

  const [summary, channels] = await Promise.all([
    getAIvsHumanSummary(profile.company_id, periodStart),
    getChannelSummary(profile.company_id, periodStart, periodEnd),
  ])

  const aiTotal = summary.ai + summary.ai_assisted
  const total = summary.ai + summary.ai_assisted + summary.human
  const aiShare = total > 0 ? Math.round((aiTotal / total) * 100) : 0
  const humanShare = total > 0 ? Math.round((summary.human / total) * 100) : 0

  return (
    <div className="space-y-6">
      <div>
        <h1 className="font-display font-bold text-3xl text-slate-900">
          AI Revenue Attribution
        </h1>
        <p className="text-slate-500 mt-1">
          See how much collection revenue was generated by AI, AI-assisted work, and human collectors during the last 30 days.
        </p>
      </div>

      <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
        <StatCard
          title="AI Collected"
          value={`${Math.round(summary.ai).toLocaleString()} SAR`}
          sub={`${summary.ai_count} payments directly attributed to AI`}
        />
        <StatCard
          title="AI Assisted"
          value={`${Math.round(summary.ai_assisted).toLocaleString()} SAR`}
          sub="Payments where AI helped the process"
        />
        <StatCard
          title="Human Collected"
          value={`${Math.round(summary.human).toLocaleString()} SAR`}
          sub={`${summary.human_count} collector payments`}
        />
        <StatCard
          title="AI Share"
          value={`${aiShare}%`}
          sub={`Human share ${humanShare}%`}
        />
      </div>

      <div className="card p-6">
        <h2 className="font-display font-semibold text-xl text-slate-900 mb-4">
          Collection Attribution by Channel
        </h2>

        {channels.length === 0 ? (
          <div className="text-slate-500 text-sm">
            No revenue attribution data yet. New payments recorded from now on will appear here.
          </div>
        ) : (
          <div className="space-y-3">
            {channels.map((row) => (
              <div key={row.channel} className="flex items-center justify-between border-b border-slate-200 pb-3">
                <div>
                  <div className="text-slate-900 font-medium capitalize">{row.channel.replace('_', ' ')}</div>
                  <div className="text-slate-400 text-xs">
                    {row.count} payments · Avg days {row.avg_days} · Avg ROI {row.avg_roi}%
                  </div>
                </div>
                <div className="text-slate-900 font-semibold">
                  <Money value={row.total_amount} />
                </div>
              </div>
            ))}
          </div>
        )}
      </div>

      <div className="card p-6">
        <h2 className="font-display font-semibold text-xl text-slate-900 mb-2">
          How this works
        </h2>
        <p className="text-slate-500 text-sm leading-6">
          When a payment is recorded, the system stores a revenue attribution event.
          This makes it possible to calculate how much money came from AI actions,
          AI-assisted collections, campaigns, or human collectors.
        </p>
      </div>
    </div>
  )
}
